# Generated by Django 4.2.2 on 2023-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=400)),
                ('imageUrl', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'homeGrid',
            },
        ),
    ]
