# Generated by Django 4.2.2 on 2023-08-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegrid',
            name='details',
            field=models.CharField(default='some strin', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homegrid',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
